### ISSUE TITLE
Create various labels [Question]?

### ISSUE THREAD

**Issue by code4cake** [Kartikkh/WeDonateMobileApp#10]
Hey what about adding other labels, to help with the development and keep us aligned?

  -  [ ] needs-test
 -  [ ] discussion
 -  [x] claimed
-  [ ] ...

**Comment by Kartikkh** [comment]
what does that mean ?

**Comment by Kartikkh** [comment]
@dantesolis  where should i create ?

**Comment by akshayvinchurkar1** [comment]
ok go to issues then lick on labels button next to filters textfield and add new labels their
